husainapp/hotel/urls.py
from django.conf.urls import url
from hotel import views as hotel_views
app_name = 'hotel'
urlpatterns = [
    #url(r'^$',hotel_views.index, name='index'),
    url(r'^categories/(?P<pk>[0-9]+)$', hotel_views.hoteldetails, name='hoteldetails'),
    url(r'^categories/create$', hotel_views.hotelcreate, name='hotelcreate'),
]

husainapp/husainapp/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from hotel import views
from registration.backends.simple.views import RegistrationView
app_name = 'husainapp'

class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return '/'
urlpatterns = [
    url(r'^$',views.index, name='index'),
    url(r'^hotels/', include('hotel.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/register/$',MyRegistrationView.as_view(), name='registration_register'),
    url(r'^accounts/', include('registration.backends.simple.urls')),


]

husainapp/hotel/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django import forms
class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)

    def __str__(self):
        return self.name


class Page(models.Model):
    Category = models.ForeignKey(Category)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title

husainapp/hotel/forms.py
from django import forms
from hotel.models import Category , Page
class Catform(forms.ModelForm):
    class Meta:
        model = Category;
        fields = ['name'];

husainapp/hotel/views.py
from django.shortcuts import render,redirect

from django.http import HttpResponse
from django.http import HttpResponseRedirect
from hotel.models import Category
from hotel.forms import Catform

def index(request):
        category_list = Category.objects.all()
        context_dict = {'categories': category_list}
        return render(request, 'hotel/index.html', context_dict)
def hotelcreate(request):
    if request.method == "GET":
        form = Catform();
        return render(request, 'hotel/addcat.html', {'form':form});
    elif request.method == "POST":
        form = Catform(request.POST);
        form.save();
        return redirect('index')
def hoteldetails(request, pk):

    #thehotel = Category.objects.filter(id = pk)[0]
    thehotel = Category.objects.get(id = pk)
    context = {'category': thehotel}
    return render(request, 'hotel/hoteldetails.html', context)

husainapp/templates/hotel/addcat.html
{% extends "layouts/base.html" %}
{% block content %}

    <form method="post">
       {% csrf_token %}
       {{form}}
       <button type="submit">save</button>
    </form>
{% endblock %}

husainapp/templates/hotel/hoteldetails.html
{% extends "layouts/base.html" %}
{% block content %}
    <h2>{{ category.name }}</h2>
    <h2>{{ category.name }}</h2>


    <h3></h3>
{% endblock %}

husainapp/templates/hotel/index.html
{% extends "layouts/base.html" %}
{% load staticfiles %}
{% block content %}


         {% if categories %}
           <ul class="list-group">
             {% for category in categories %}
               <!-- <a href ="hotels/categories/{{category.id}}"><li> -->
               <a href ="{% url 'hotel:hoteldetails' category.id %}"><li class="list-group-item">
                 {{ category.name }}
               </li></a>
               {% endfor %}
           </ul>
           {% else %}
             <strong>No categories</strong>
            {% endif %}


      <a href="/hotel/about/">About</a>
      <img src="{% static "images/tajmahal.jpg" %}"  alt="Picture of Taj India" />
 {% endblock %}

husainapp/templates/layouts/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Check-In</title>

    <!-- Bootstrap core CSS -->
    <link href="http://v4-alpha.getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="https://v4-alpha.getbootstrap.com/examples/starter-template/starter-template.css" rel="stylesheet">
  </head>

  <body>

    <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse fixed-top">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="#">Check In</a>

      <div id="navbar">
<nav class="nav navbar-nav pull-xs-left">
<a class="nav-item nav-link" href="{% url 'index' %}">Home</a>
{% if user.is_authenticated %}
<a class="nav-item nav-link"
href="{% url 'index' %}">
Home</a>
<a class="nav-item nav-link"
href="{% url 'auth_logout' %}?next=/">Logout</a>
{% else %}
<a class="nav-item nav-link"
href="{% url 'registration_register' %}">Register Here</a>
<a class="nav-item nav-link"
href="{% url 'auth_login' %}">Login</a>
{% endif %}
</nav>
</div>
</nav>
      </div>
    </nav>

    <div class="container">

      <div class="starter-template">
        {% block content %}

        {% endblock %}
      </div>

    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>